(ns ^:deprecated propagators.compiler-2.cps-core
  "Deprecated namespace shim; use `propagators.compiler-2.compiler.cps`."
  (:refer-clojure :exclude [symbol?])
  (:require [propagators.compiler-2.compiler.cps :as cps]
            [propagators.compiler-2.compiler.handlers :as handlers]
            [propagators.compiler-2.compiler.predicates :as predicates]))

(def compiler-result-key cps/compiler-result-key)
(def compiler-props-key cps/compiler-props-key)
(def compiler-applications-key cps/compiler-applications-key)

(def literal? predicates/literal?)
(def symbol? predicates/symbol?)
(def sequence? predicates/sequence?)
(def let-cell? predicates/let-cell?)
(def let? predicates/let?)
(def when-topology? predicates/when-topology?)
(def network? predicates/network?)
(def compound? predicates/compound?)
(def def-net? predicates/def-net?)
(def def-constraint? predicates/def-constraint?)
(def definition? predicates/definition?)
(def def-cell? predicates/def-cell?)

(def compile-literal handlers/compile-literal)
(def compile-symbol handlers/compile-symbol)
(def compile-sequence handlers/compile-sequence)
(def compile-let-cell handlers/compile-let-cell)
(def compile-let handlers/compile-let)
(def compile-when-topology handlers/compile-when-topology)
(def compile-network-form handlers/compile-network-form)
(def compile-compound handlers/compile-compound)
(def compile-def-net handlers/compile-def-net)
(def compile-def-constraint handlers/compile-def-constraint)
(def compile-def handlers/compile-def)
(def compile-def-cell handlers/compile-def-cell)
(def compile-application handlers/compile-application)

(def compiler-dispatch cps/compiler-dispatch)
(def compile* cps/compile*)
(def ^:deprecated default-compiler cps/default-compiler)
(def compile-expr cps/compile-expr)
(def compile-source cps/compile-source)
(def compiled-result cps/compiled-result)
(def compiled-props cps/compiled-props)
(def compiled-applications cps/compiled-applications)
(def p:compile-expr cps/p:compile-expr)
(def p:execute-sub-env cps/p:execute-sub-env)
